###GET ALL USERS
POST http://localhost:8080/rest/search
Content-Type: application/json

{
  "resultType": "USER"
}

###
###GET ALL PROJECT
POST http://localhost:8080/rest/search
Content-Type: application/json

{
  "resultType": "PROJECT"
}

###
###GET ALL FEATURE
POST http://localhost:8080/rest/search
Content-Type: application/json

{
  "resultType": "FEATURE"
}

###
###GET ALL TASK
POST http://localhost:8080/rest/search
Content-Type: application/json

{
  "resultType": "TASK"
}